#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 14

enum ts_symbol_identifiers {
  anon_sym_DOLLAR = 1,
  anon_sym_SEMI = 2,
  anon_sym_COLON = 3,
  anon_sym_COLON_COLON = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_LBRACK = 8,
  anon_sym_RBRACK = 9,
  anon_sym_block = 10,
  anon_sym_DASH = 11,
  anon_sym_SLASH = 12,
  anon_sym_PLUS = 13,
  anon_sym_STAR = 14,
  sym_identifier = 15,
  sym_number = 16,
  anon_sym_SLASH_STAR = 17,
  anon_sym_STAR_SLASH = 18,
  aux_sym__comment_text_token1 = 19,
  sym__whitespace = 20,
  sym_source_file = 21,
  sym_statement = 22,
  sym_expression = 23,
  sym_assign = 24,
  sym_assign_eval = 25,
  sym__atom = 26,
  sym__bracket_expression = 27,
  sym_function_call = 28,
  sym__function_arguments = 29,
  sym_list = 30,
  sym_block = 31,
  sym__unary_function = 32,
  sym_unary_minus = 33,
  sym__binary_function = 34,
  sym_subtraction = 35,
  sym_division = 36,
  sym__nary_function = 37,
  sym_addition = 38,
  sym_multiplication = 39,
  sym_comment = 40,
  aux_sym__comment_text = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym__function_arguments_repeat1 = 43,
  aux_sym_addition_repeat1 = 44,
  aux_sym_multiplication_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_block] = "block",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym__comment_text_token1] = "_comment_text_token1",
  [sym__whitespace] = "_whitespace",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_expression] = "expression",
  [sym_assign] = "assign",
  [sym_assign_eval] = "assign_eval",
  [sym__atom] = "_atom",
  [sym__bracket_expression] = "_bracket_expression",
  [sym_function_call] = "function_call",
  [sym__function_arguments] = "_function_arguments",
  [sym_list] = "list",
  [sym_block] = "block",
  [sym__unary_function] = "_unary_function",
  [sym_unary_minus] = "unary_minus",
  [sym__binary_function] = "_binary_function",
  [sym_subtraction] = "subtraction",
  [sym_division] = "division",
  [sym__nary_function] = "_nary_function",
  [sym_addition] = "addition",
  [sym_multiplication] = "multiplication",
  [sym_comment] = "comment",
  [aux_sym__comment_text] = "_comment_text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__function_arguments_repeat1] = "_function_arguments_repeat1",
  [aux_sym_addition_repeat1] = "addition_repeat1",
  [aux_sym_multiplication_repeat1] = "multiplication_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym__comment_text_token1] = aux_sym__comment_text_token1,
  [sym__whitespace] = sym__whitespace,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_expression] = sym_expression,
  [sym_assign] = sym_assign,
  [sym_assign_eval] = sym_assign_eval,
  [sym__atom] = sym__atom,
  [sym__bracket_expression] = sym__bracket_expression,
  [sym_function_call] = sym_function_call,
  [sym__function_arguments] = sym__function_arguments,
  [sym_list] = sym_list,
  [sym_block] = sym_block,
  [sym__unary_function] = sym__unary_function,
  [sym_unary_minus] = sym_unary_minus,
  [sym__binary_function] = sym__binary_function,
  [sym_subtraction] = sym_subtraction,
  [sym_division] = sym_division,
  [sym__nary_function] = sym__nary_function,
  [sym_addition] = sym_addition,
  [sym_multiplication] = sym_multiplication,
  [sym_comment] = sym_comment,
  [aux_sym__comment_text] = aux_sym__comment_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__function_arguments_repeat1] = aux_sym__function_arguments_repeat1,
  [aux_sym_addition_repeat1] = aux_sym_addition_repeat1,
  [aux_sym_multiplication_repeat1] = aux_sym_multiplication_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__comment_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_assign_eval] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym__bracket_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__function_arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__unary_function] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_minus] = {
    .visible = true,
    .named = true,
  },
  [sym__binary_function] = {
    .visible = false,
    .named = true,
  },
  [sym_subtraction] = {
    .visible = true,
    .named = true,
  },
  [sym_division] = {
    .visible = true,
    .named = true,
  },
  [sym__nary_function] = {
    .visible = false,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplication] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__comment_text] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__function_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_addition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiplication_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_function = 2,
  field_multiplicand = 3,
  field_summand = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_function] = "function",
  [field_multiplicand] = "multiplicand",
  [field_summand] = "summand",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 1},
  [12] = {.index = 17, .length = 1},
  [13] = {.index = 18, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 0},
  [1] =
    {field_summand, 0},
  [2] =
    {field_multiplicand, 0},
  [3] =
    {field_summand, 0, .inherited = true},
    {field_summand, 1},
  [5] =
    {field_summand, 0, .inherited = true},
    {field_summand, 1, .inherited = true},
  [7] =
    {field_multiplicand, 0, .inherited = true},
    {field_multiplicand, 1},
  [9] =
    {field_multiplicand, 0, .inherited = true},
    {field_multiplicand, 1, .inherited = true},
  [11] =
    {field_argument, 1, .inherited = true},
  [12] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1},
  [14] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [16] =
    {field_function, 0},
  [17] =
    {field_argument, 2, .inherited = true},
  [18] =
    {field_argument, 2, .inherited = true},
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '$', 5,
        '(', 10,
        ')', 11,
        '*', 20,
        '+', 18,
        ',', 12,
        '-', 16,
        '/', 17,
        ':', 7,
        ';', 6,
        '[', 13,
        ']', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(32);
      if (lookahead == '/') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '$', 5,
        '(', 10,
        ')', 11,
        '*', 19,
        '+', 18,
        ',', 12,
        '-', 16,
        '/', 17,
        ':', 8,
        ';', 6,
        '[', 13,
        ']', 14,
        'b', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(9);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_block);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(28);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__comment_text_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__comment_text_token1);
      if (lookahead == '*') ADVANCE(28);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__comment_text_token1);
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__whitespace);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {(TSStateId)(-1)},
  [59] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [aux_sym__comment_text_token1] = ACTIONS(1),
    [sym__whitespace] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(53),
    [sym_statement] = STATE(39),
    [sym_expression] = STATE(46),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [2] = {
    [sym_expression] = STATE(42),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym__function_arguments] = STATE(57),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(2),
    [aux_sym__function_arguments_repeat1] = STATE(7),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [3] = {
    [sym_statement] = STATE(39),
    [sym_expression] = STATE(46),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(30),
    [anon_sym_block] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(36),
    [sym_identifier] = ACTIONS(39),
    [sym_number] = ACTIONS(42),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [4] = {
    [sym_expression] = STATE(42),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym__function_arguments] = STATE(54),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(4),
    [aux_sym__function_arguments_repeat1] = STATE(7),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [5] = {
    [sym_statement] = STATE(39),
    [sym_expression] = STATE(46),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [6] = {
    [sym_expression] = STATE(42),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym__function_arguments] = STATE(56),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(6),
    [aux_sym__function_arguments_repeat1] = STATE(7),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [7] = {
    [sym_expression] = STATE(40),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(7),
    [aux_sym__function_arguments_repeat1] = STATE(8),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [8] = {
    [sym_expression] = STATE(47),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(8),
    [aux_sym__function_arguments_repeat1] = STATE(8),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(54),
    [anon_sym_block] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(60),
    [sym_identifier] = ACTIONS(63),
    [sym_number] = ACTIONS(66),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [9] = {
    [sym_expression] = STATE(48),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(9),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [10] = {
    [sym_expression] = STATE(37),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(10),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [11] = {
    [sym_expression] = STATE(28),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(11),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [12] = {
    [sym_expression] = STATE(38),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(12),
    [aux_sym_addition_repeat1] = STATE(12),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [13] = {
    [sym_expression] = STATE(22),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(13),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [14] = {
    [sym_expression] = STATE(24),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(14),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [15] = {
    [sym_expression] = STATE(27),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(15),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [16] = {
    [sym_expression] = STATE(32),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(16),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [17] = {
    [sym_expression] = STATE(38),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(17),
    [aux_sym_addition_repeat1] = STATE(12),
    [aux_sym_multiplication_repeat1] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
  [18] = {
    [sym_expression] = STATE(37),
    [sym_assign] = STATE(33),
    [sym_assign_eval] = STATE(33),
    [sym__atom] = STATE(33),
    [sym__bracket_expression] = STATE(33),
    [sym_function_call] = STATE(33),
    [sym_list] = STATE(33),
    [sym_block] = STATE(33),
    [sym__unary_function] = STATE(33),
    [sym_unary_minus] = STATE(31),
    [sym__binary_function] = STATE(33),
    [sym_subtraction] = STATE(20),
    [sym_division] = STATE(20),
    [sym__nary_function] = STATE(33),
    [sym_addition] = STATE(30),
    [sym_multiplication] = STATE(30),
    [sym_comment] = STATE(18),
    [aux_sym_addition_repeat1] = STATE(17),
    [aux_sym_multiplication_repeat1] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_block] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [sym__whitespace] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(71), 1,
      anon_sym_COLON,
    ACTIONS(73), 1,
      anon_sym_COLON_COLON,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      sym_comment,
    ACTIONS(69), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [32] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(81), 1,
      anon_sym_SLASH,
    STATE(20), 1,
      sym_comment,
    ACTIONS(79), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [55] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    STATE(21), 1,
      sym_comment,
    ACTIONS(83), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [78] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(89), 1,
      anon_sym_SLASH,
    STATE(22), 1,
      sym_comment,
    ACTIONS(87), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [101] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(93), 1,
      anon_sym_SLASH,
    STATE(23), 1,
      sym_comment,
    ACTIONS(91), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [124] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    STATE(24), 1,
      sym_comment,
    ACTIONS(95), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [147] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(101), 1,
      anon_sym_SLASH,
    STATE(25), 1,
      sym_comment,
    ACTIONS(99), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [170] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(105), 1,
      anon_sym_SLASH,
    STATE(26), 1,
      sym_comment,
    ACTIONS(103), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [193] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_PLUS,
    ACTIONS(113), 1,
      anon_sym_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(107), 5,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [222] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(115), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [245] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(119), 1,
      anon_sym_SLASH,
    STATE(29), 1,
      sym_comment,
    ACTIONS(117), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [268] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(123), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(121), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [291] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(127), 1,
      anon_sym_SLASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(125), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [314] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_PLUS,
    ACTIONS(113), 1,
      anon_sym_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(129), 5,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [343] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(133), 1,
      anon_sym_SLASH,
    STATE(33), 1,
      sym_comment,
    ACTIONS(131), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [366] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(137), 1,
      anon_sym_SLASH,
    STATE(34), 1,
      sym_comment,
    ACTIONS(135), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [389] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(141), 1,
      anon_sym_SLASH,
    STATE(35), 1,
      sym_comment,
    ACTIONS(139), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [412] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    STATE(36), 1,
      sym_comment,
    ACTIONS(69), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [435] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    STATE(37), 1,
      sym_comment,
    ACTIONS(143), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [458] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(147), 1,
      anon_sym_SLASH,
    STATE(38), 1,
      sym_comment,
    ACTIONS(145), 8,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_STAR,
  [481] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    STATE(39), 1,
      sym_comment,
    ACTIONS(151), 2,
      anon_sym_block,
      sym_identifier,
    ACTIONS(149), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      sym_number,
  [502] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_PLUS,
    ACTIONS(113), 1,
      anon_sym_STAR,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(40), 1,
      sym_comment,
    ACTIONS(153), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [531] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    STATE(41), 1,
      sym_comment,
    ACTIONS(159), 2,
      anon_sym_block,
      sym_identifier,
    ACTIONS(157), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      sym_number,
  [552] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_PLUS,
    ACTIONS(113), 1,
      anon_sym_STAR,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(42), 1,
      sym_comment,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [581] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    STATE(43), 1,
      sym_comment,
    ACTIONS(165), 2,
      anon_sym_block,
      sym_identifier,
    ACTIONS(163), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      sym_number,
  [601] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    STATE(44), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_block,
      sym_identifier,
    ACTIONS(167), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      sym_number,
  [621] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    STATE(45), 1,
      sym_comment,
    ACTIONS(173), 2,
      anon_sym_block,
      sym_identifier,
    ACTIONS(171), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_DASH,
      sym_number,
  [641] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_PLUS,
    ACTIONS(113), 1,
      anon_sym_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(175), 2,
      anon_sym_DOLLAR,
      anon_sym_SEMI,
  [667] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_PLUS,
    ACTIONS(113), 1,
      anon_sym_STAR,
    ACTIONS(155), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      sym_comment,
  [692] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(97), 1,
      anon_sym_SLASH,
    ACTIONS(109), 1,
      anon_sym_DASH,
    ACTIONS(111), 1,
      anon_sym_PLUS,
    ACTIONS(113), 1,
      anon_sym_STAR,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      sym_comment,
  [717] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__whitespace,
    ACTIONS(179), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(181), 1,
      aux_sym__comment_text_token1,
    STATE(49), 1,
      sym_comment,
    STATE(50), 1,
      aux_sym__comment_text,
  [736] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__whitespace,
    ACTIONS(183), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(185), 1,
      aux_sym__comment_text_token1,
    STATE(50), 2,
      sym_comment,
      aux_sym__comment_text,
  [753] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__whitespace,
    ACTIONS(181), 1,
      aux_sym__comment_text_token1,
    ACTIONS(188), 1,
      anon_sym_STAR_SLASH,
    STATE(49), 1,
      aux_sym__comment_text,
    STATE(51), 1,
      sym_comment,
  [772] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(5), 1,
      sym__whitespace,
    ACTIONS(190), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(192), 1,
      aux_sym__comment_text_token1,
    STATE(52), 1,
      sym_comment,
  [788] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(194), 1,
      ts_builtin_sym_end,
    STATE(53), 1,
      sym_comment,
  [801] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(196), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      sym_comment,
  [814] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(198), 1,
      anon_sym_LPAREN,
    STATE(55), 1,
      sym_comment,
  [827] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(56), 1,
      sym_comment,
  [840] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      sym__whitespace,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      sym_comment,
  [853] = 1,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
  [857] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 32,
  [SMALL_STATE(21)] = 55,
  [SMALL_STATE(22)] = 78,
  [SMALL_STATE(23)] = 101,
  [SMALL_STATE(24)] = 124,
  [SMALL_STATE(25)] = 147,
  [SMALL_STATE(26)] = 170,
  [SMALL_STATE(27)] = 193,
  [SMALL_STATE(28)] = 222,
  [SMALL_STATE(29)] = 245,
  [SMALL_STATE(30)] = 268,
  [SMALL_STATE(31)] = 291,
  [SMALL_STATE(32)] = 314,
  [SMALL_STATE(33)] = 343,
  [SMALL_STATE(34)] = 366,
  [SMALL_STATE(35)] = 389,
  [SMALL_STATE(36)] = 412,
  [SMALL_STATE(37)] = 435,
  [SMALL_STATE(38)] = 458,
  [SMALL_STATE(39)] = 481,
  [SMALL_STATE(40)] = 502,
  [SMALL_STATE(41)] = 531,
  [SMALL_STATE(42)] = 552,
  [SMALL_STATE(43)] = 581,
  [SMALL_STATE(44)] = 601,
  [SMALL_STATE(45)] = 621,
  [SMALL_STATE(46)] = 641,
  [SMALL_STATE(47)] = 667,
  [SMALL_STATE(48)] = 692,
  [SMALL_STATE(49)] = 717,
  [SMALL_STATE(50)] = 736,
  [SMALL_STATE(51)] = 753,
  [SMALL_STATE(52)] = 772,
  [SMALL_STATE(53)] = 788,
  [SMALL_STATE(54)] = 801,
  [SMALL_STATE(55)] = 814,
  [SMALL_STATE(56)] = 827,
  [SMALL_STATE(57)] = 840,
  [SMALL_STATE(58)] = 853,
  [SMALL_STATE(59)] = 857,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 10), SHIFT_REPEAT(9),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 10), SHIFT_REPEAT(2),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 10), SHIFT_REPEAT(55),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 10), SHIFT_REPEAT(11),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 10), SHIFT_REPEAT(19),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 10), SHIFT_REPEAT(36),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary_function, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__binary_function, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 8),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 8),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_division, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtraction, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 13),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 13),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 11),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 11),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign_eval, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_minus, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 12),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 12),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__nary_function, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__nary_function, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unary_function, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__unary_function, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bracket_expression, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__bracket_expression, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplication, 2, 0, 6),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 2, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 2, 0, 4),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_arguments, 2, 0, 9),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function_arguments, 1, 0, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiplication_repeat1, 2, 0, 3),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multiplication_repeat1, 2, 0, 3),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 2),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__function_arguments_repeat1, 2, 0, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_text, 2, 0, 0),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__comment_text, 2, 0, 0), SHIFT_REPEAT(52),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__comment_text, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__comment_text, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_maxima(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
